version: '2'

services:
  database:
    image: mariadb:10.5
    environment:
      - MARIADB_USER=redmine
      - MARIADB_PASSWORD=superstrangepass
      - MARIADB_DATABASE=redmine_production
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    volumes:
      - /volume3/docker/redmine/db:/var/lib/mysql

  redmine:
    build: ./
    image: sameersbn/redmine:5.1.1
    depends_on:
      - database
    environment:
      - TZ=Europe/Minsk

      - DB_ADAPTER=mysql2
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production
      - DB_SSL_MODE=preferred

      - REDMINE_PORT=10083
      - REDMINE_HTTPS=false

      - REDMINE_SUDO_MODE_ENABLED=false
      - REDMINE_SUDO_MODE_TIMEOUT=15

      - REDMINE_CONCURRENT_UPLOADS=2

      - SMTP_ENABLED=false
      - SMTP_METHOD=smtp
      - SMTP_DOMAIN=www.example.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=mailer@example.com
      - SMTP_PASS=password
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=:login

    ports:
      - "3434:3000"
    volumes:
      - /volume3/docker/redmine/data:/home/redmine/data
      - /volume3/docker/redmine/redmine-logs:/var/log/redmine
